export const INSURANCE_PLANS: readonly string[] = [
  "1199 Benefit Plan",
  "Aetna Better Health",
  "Amerivantage (Amerigroup) HMO",
  "CHN",
  "Empire BC/BS",
  "Horizon NJ Health",
  "Horizon POS",
  "Humana Choice PPO",
  "Medicare — Straight / Traditional",
  "PHS (Healthnet)",
  "Tricare",
  "WellCare",
  "Aetna PPO",
  "Aetna Open Choice",
  "Amerihealth",
  "Cigna PPO/HMO",
  "Horizon BCBS PPO/HMO",
  "Horizon NJ Health Complete (SNP)",
  "Horizon Medicare Blue PPO/HMO",
  "Magna Care",
  "Oxford (United) PPO / HMO",
  "QualCare",
  "UnitedHealthcare AARP Medicare COMPLETE HMO",
  "WellCare Medicare Advantage",
  "Aetna POS/EPO",
  "Amerigroup",
  "CCN (Community Care Network)",
  "Clover PPO/HMO",
  "Direct Access",
  "Horizon OMNIA",
  "Horizon Advantage",
  "Medicaid / NJ Family Care",
  "PHCS (Private Healthcare)",
  "Oscar",
  "UnitedHealthcare Community Plan",
] as const;