export const INSURANCE_PLANS = [
	"1199 Benefit Plan",
	"Aetna PPO",
	"Aetna POS/EPO",
	"Aetna Better Health",
	"Aetna Open Choice",
	"Amerigroup",
	"Amerivantage (Amerigroup) HMO",
	"Amerihealth",
	"CCN (Community Care Network)",
	"CHN",
	"Cigna PPO/HMO",
	"Clover PPO/HMO",
	"Empire BC/BS",
	"Horizon BCBS PPO/HMO",
	"Direct Access",
	"Horizon NJ Health",
	"Horizon NJ Health Complete (SNP)",
	"Horizon OMNIA",
	"Horizon POS",
	"Horizon Medicare Blue PPO/HMO",
	"Horizon Advantage",
	"Humana Choice PPO",
	"Magna Care",
	"Medicaid / NJ Family Care",
	"Medicare — Straight / Traditional",
	"Oxford (United) PPO / HMO",
	"PHCS (Private Healthcare)",
	"PHS (Healthnet)",
	"QualCare",
	"Oscar",
	"Tricare",
	"UnitedHealthcare AARP Medicare COMPLETE HMO",
	"UnitedHealthcare Community Plan",
	"WellCare",
	"WellCare Medicare Advantage",
]
