type Services = {
	[key: string]: string[]
}

export const SERVICES: Services = {
	"General Health": [
		"Long-term treatment of chronic illnesses",
		"Problem-based treatment of acute illnesses (sick visit)",
		"Immunizations and vaccinations",
		"Sports physicals",
		"School and college physicals",
		"Employment physicals",
		"Annual preventive and wellness visit",
		"Diagnostic and preventing screening",
		"Gynecological screening",
		"Contraception",
		"Substance abuse counseling",
		"Weight loss",
		"Pre-operative medical clearance",
		"LGBTQ+ health",
		"Telehealth",
	],
	"Diagnostic Screening": [
		"Malaria prophylaxis",
		"Blood pressure screening",
		"Diabetes mellitus screening",
		"Cholesterol screening",
		"Thyroid disorder screening",
		"Blood disorder screening",
		"Obesity screening",
		"Kidney disease screening",
		"Lung cancer screening",
		"Prostate cancer screening",
		"Hepatitis B and C screening",
		"HIV screening",
		"STD screening",
		"Ovarian cancer screening",
		"Uterine cancer screening",
		"Breast cancer screening",
		"Mental health screening",
		"Osteoporosis screening",
		"Substance abuse screening",
	],
	"Preventive Screening": [
		"Breast cancer screening",
		"Cervical cancer screening",
		"Colon cancer screening",
		"Prostate cancer screening",
		"Ovarian cancer screening",
		"STD screening",
	],
	"Office Tests and Procedures": [
		"ECG/EKG",
		"Laboratory services",
		"Metabolic testing",
		"Tuberculosis testing",
		"Pap smear",
		"STD testing",
	],
	"Therapeutic Injections": ["B12 injection", "Depo-medrol injection"],
	Vaccinations: [
		"Hepatitis B",
		"Influenza",
		"TD",
		"TDAP",
		"MMR",
		"Zostavax",
		"Menactra",
	],
}
