import { ServiceGroup } from "./interfaces"

export const SERVICES: ServiceGroup[] = [
	{
		title: "General Health",
		services: [
			{ title: "Treatment of acute & chronic illnesses" },
			{ title: "Preventive and wellness visit (annual)" },
			{ title: "Diagnostic and preventive screening" },
			{
				title: "Immunization/vaccinations",
				note: "Limited as covered by individual insurance.",
			},
			{ title: "School/college physical" },
			{ title: "Employment physical" },
			{ title: "Pre-operative consultation & medical clearance" },
			{ title: "Malaria prophylaxis" },
		],
	},
	{
		title: "Diagnostic Screening",
		services: [
			{ title: "Malaria prophylaxis" },
			{ title: "Blood pressure screening" },
			{ title: "Diabetes mellitus screening" },
			{ title: "Cholesterol screening" },
			{ title: "Thyroid disorder screening" },
			{ title: "Asthma screening" },
			{ title: "Anemia screening" },
			{ title: "Obesity screening" },
			{ title: "Kidney disease screening" },
			{ title: "Lung cancer screening" },
			{ title: "Prostate cancer screening" },
			{ title: "Hepatitis B and C screening" },
			{ title: "HIV screening" },
			{ title: "STD screening" },
			{ title: "Ovarian cancer screening" },
			{ title: "Uterine cancer screening" },
			{ title: "Breast Cancer Screening" },
			{ title: "Depression Screening" },
			{ title: "Anxiety Screening" },
			{ title: "Osteopenia Screening" },
			{ title: "Osteoporosis Screening" },
		],
	},
	{
		title: "Preventive Screening",
		services: [
			{ title: "Breast cancer screening" },
			{ title: "Cervical cancer screening" },
			{ title: "Colon cancer screening" },
			{ title: "Prostate Cancer Screening" },
			{ title: "Ovarian cancer Screening" },
			{ title: "Pap smear and HRT Screening" },
			{ title: "STD Screening" },
		],
	},
	{
		title: "Office Tests and Procedures",
		services: [
			{ title: "ECG/EKG" },
			{ title: "Laboratory services" },
			{ title: "Metabolic testing" },
			{ title: "Pulmonary function test" },
			{ title: "TB testing" },
			{ title: "Pap smear" },
			{ title: "STD testing" },
		],
	},
	{
		title: "Therapeutic Injections",
		services: [
			{ title: "B12 injection" },
			{ title: "Benadryl injection" },
			{ title: "Solu-medrol injection" },
		],
	},
	{
		title: "Vaccinations",
		services: [
			{ title: "Hepatitis B" },
			{ title: "Influenza" },
			{ title: "TD", note: "May involve additional charges." },
			{ title: "TDAP", note: "May involve additional charges." },
			{ title: "MMR", note: "May involve additional charges." },
			{ title: "Zostavax", note: "May involve additional charges." },
			{ title: "Menactra", note: "May involve additional charges." },
		],
	},
	{
		title: "Acute Medical Conditions",
		services: [
			{ title: "Allergies" },
			{ title: "Asthma" },
			{ title: "Cold and flu" },
			{ title: "Ear, nose, & throat diseases" },
			{ title: "Gastrointestinal illnesses" },
			{ title: "Lyme Disease" },
			{ title: "Pink eye" },
			{ title: "Acute grief Reaction" },
			{ title: "Respiratory illnesses" },
			{ title: "Sinus infections" },
			{ title: "Skin ailments" },
			{ title: "Strep throat" },
			{ title: "Urinary tract infection" },
			{
				title: "Injury",
				note: "Not related to Workman's Comp or MVA.",
			},
			{ title: "Bites and stings" },
			{ title: "Minor burns" },
			{ title: "Cuts and scrapes" },
			{ title: "Sprain" },
			{ title: "Coronavirus" },
		],
	},
	{
		title: "Chronic Medical Conditions",
		services: [
			{ title: "Hypertension" },
			{ title: "Diabetes" },
			{ title: "Hyperlipidemia" },
			{ title: "Thyroid disorder" },
			{ title: "Asthma" },
			{ title: "COPD" },
			{ title: "CVA" },
			{ title: "ASCAD" },
			{ title: "Dementia" },
			{ title: "Malignancy supportive care" },
			{ title: "Arthritis" },
			{ title: "Osteoporosis and Osteopenia" },
			{ title: "Menopause" },
			{ title: "Low back pain & joint pain" },
			{
				title: "Weight Loss management",
				note: "Insurance exempt. Only at Rahway.",
			},
			{ title: "Smoking cessation" },
			{ title: "Vasculitis" },
			{ title: "Depression" },
			{ title: "Generalized Anxiety Disorder" },
			{ title: "Rheumatoid arthritis" },
			{
				title:
					"Lupus and other Vasculitis concurrent management and supportive care",
			},
			{ title: "Malignancy concurrent management and supportive care" },
		],
	},
]
