import { ServiceGroup } from "./interfaces"

export const SERVICES: ServiceGroup[] = [
	{
		title: "General Health",
		services: [
			{ title: "Long-term treatment of chronic illnesses" },
			{ title: "Problem-based treatment of acute illnesses (sick visit)" },
			{
				title: "Immunizations/Vaccinations",
				note: "Limited as covered by individual insurance.",
			},
			{ title: "Sports physical" },
			{ title: "School/College physicals" },
			{ title: "Employment physical" },
			{ title: "Annual preventive and wellness visit" },
			{ title: "Diagnostic and preventing screening" },
			{ title: "Gynecological screening" },
			{ title: "Contraception" },
			{ title: "Substance abuse counseling" },
			{ title: "Weight Loss" },
			{ title: "Pre-operative medical clearance" },
			{ title: "LGBTQ+ health " },
			{ title: "Telehealth" },
		],
	},
	{
		title: "Diagnostic Screening",
		services: [
			{ title: "Malaria prophylaxis" },
			{ title: "Blood pressure screening" },
			{ title: "Diabetes mellitus screening" },
			{ title: "Cholesterol screening" },
			{ title: "Thyroid disorder screening" },
			{ title: "Blood disorder screening" },
			{ title: "Obesity screening" },
			{ title: "Kidney disease screening" },
			{ title: "Lung cancer screening" },
			{ title: "Prostate cancer screening" },
			{ title: "Hepatitis B and C screening" },
			{ title: "HIV screening" },
			{ title: "STD screening" },
			{ title: "Ovarian cancer screening" },
			{ title: "Uterine cancer screening" },
			{ title: "Breast cancer screening" },
			{ title: "Mental health screening" },
			{ title: "Osteoporosis screening" },
			{ title: "Substance abuse screening" },
		],
	},
	{
		title: "Preventive Screening",
		services: [
			{ title: "Breast cancer screening" },
			{ title: "Cervical cancer screening" },
			{ title: "Colon cancer screening" },
			{ title: "Prostate cancer screening" },
			{ title: "Ovarian cancer screening" },
			{ title: "STD screening" },
		],
	},
	{
		title: "Office Tests and Procedures",
		services: [
			{ title: "ECG/EKG" },
			{ title: "Laboratory services" },
			{ title: "Metabolic testing" },
			{ title: "Tuberculosis testing" },
			{ title: "Pap smear" },
			{ title: "STD testing" },
		],
	},
	{
		title: "Therapeutic Injections",
		services: [{ title: "B12 injection" }, { title: "Depo-medrol injection" }],
	},
	{
		title: "Vaccinations",
		services: [
			{ title: "Hepatitis B" },
			{ title: "Influenza" },
			{ title: "TD", note: "May involve additional charges." },
			{ title: "TDAP", note: "May involve additional charges." },
			{ title: "MMR", note: "May involve additional charges." },
			{ title: "Zostavax", note: "May involve additional charges." },
			{ title: "Menactra", note: "May involve additional charges." },
		],
	},
]
